library(readr)
cereal <- read_csv("C:/Users/Shehroz Jawad Khan/Desktop/LEI Internship/Task4/cereal.csv")
str(cereal)
summary(cereal)
library(psych)
pairs.panels(cereal[,-c(1,2,3)]) 
cereal = cereal[,-1] 
max = apply(cereal[,-1] ,2, max) 
min = apply(cereal[,-1],2, min) 
scaled = as.data.frame(scale(cereal[,-1],center =min,scale =max - min)) 
smp_size <- floor(0.80 *nrow (scaled)) 
train_ind <- sample(seq_len(nrow(scaled)),size =smp_size) 
train_cereal_scaled <-scaled[train_ind, ] 
test_cereal_scaled <-scaled[ -train_ind, ]
library(neuralnet) 
ANN_model = neuralnet(rating~fat+vitamins+protein,data =train_cereal_scaled, hidden = c(3,2),linear.output =TRUE) 
plot(as.vector(ANN_model$net.result[[1]]), train_cereal_scaled$rating, xlab ="Predicted rating",ylab ="Actual rating") 
plot(ANN_model) 
cereal_test_scaled_prediction = compute(ANN_model, test_cereal_scaled[,-4]) 
test_cereal_scaled$rating_Predicted =(cereal_test_scaled_prediction $net.result * (max(cereal$rating,na.rm =T) - min(cereal$rating,na.rm =T))) +min (cereal$rating,na.rm =T) 
test_cereal_scaled$rating_Actual =(test_cereal_scaled $rating * (max(cereal$rating,na.rm =T) - min(cereal$rating,na.rm =T))) +min (cereal$rating,na.rm =T) 
plot(test_cereal_scaled$rating_Predicted, test_cereal_scaled$rating_Actual, xlab ="Predicted rating",ylab ="Actual rating") 
library(forecast)
accuracy(test_cereal_scaled$rating_Actual, test_cereal_scaled$rating_Predicted) 
